{
 "title": "Traefik Metrics",
 "description": "Traefik Metrics Dashboard",
 "tags": [
  "traefik",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job:", "query": { "query": "label_values(job)" } },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(traefik_service_requests_total{job=~\"[[job]]\"},service)"
   },
   {
    "name": "protocol",
    "label": "Protocol:",
    "query": {
     "query": "label_values(traefik_entrypoint_requests_total,protocol)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{job=~\"$job\"})/sum(traefik_entrypoint_requests_total{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Server Side Error Count last $interval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"5\\\\d\\\\d\",job=~\"$job\",service=~\"$service\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Client Side Error Count over $interval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"4\\\\d\\\\d\",service=~\"$service\",job=~\"$job\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Successful Requests over $interval",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"(2|3)\\\\d\\\\d\",service=~\"$service\",job=~\"$job\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "$protocol return code",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(traefik_service_requests_total{protocol=~\"$protocol\", job=~\"$job\", service=~\"$service\"}, \"response_code\",  \"$1,xx\", \"code\", \"(\\\\d).+\"))  by (response_code) ",
     "legendFormat": " {{response_code}}"
    }
   ]
  },
  {
   "title": "Average response time by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{job=~\"$job\",service=~\"$service\",protocol=~\"$protocol\"}) by (service) / sum(traefik_service_request_duration_seconds_count{job=~\"$job\",service=~\"$service\",protocol=~\"$protocol\"}) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "Server Side Errors by service over $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"$job\",service=~\"$service\",code=~\"5\\\\d\\\\d\",protocol=~\"$protocol\" }[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Client Side Errors by service in $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"$job\",service=~\"$service\",code=~\"4\\\\d\\\\d\",protocol=~\"$protocol\" }[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Total requests over $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\",job=~\"$job\"}[$interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Service - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{job=~\"$job\", service=~\"$service\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "ENTRYPOINT - Open Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}